backend:
  name: github
  repo: fiodarbardworks/portfolio-site
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"
publish_mode: editorial_workflow
local_backend: true
media_folder: public/img
public_folder: /img

collections:
  - name: "pages"
    label: "Основные страницы"
    delete: false
    files:
      - name: "about"
        label: "Страница About"
        file: "src/content/pages/about.md"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Описание (SEO)", name: "description", widget: "text" }
          - { label: "Порядковый номер", name: "number", widget: "number" }
          - { label: "Миниатюра (Thumbnail)", name: "thumbnail", widget: "image" }
          - { label: "Главное изображение", name: "featuredimage", widget: "image" }
          - { label: "Дата", name: "date", widget: "datetime" }
          - { label: "Текст страницы", name: "body", widget: "markdown" }
          - { label: "Тип страницы", name: "pagetype", widget: "list", default: ["main"] }
          - { label: "Шаблон", name: "templateKey", widget: "hidden", default: "about-page" }

      - name: "contact"
        label: "Страница Контакты"
        file: "src/content/pages/contact.md"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Текст страницы", name: "body", widget: "markdown" }
          - { label: "Тип страницы", name: "pagetype", widget: "list", default: ["main"] }

  - name: "works"
    label: "Ваши проекты (Индивидуальные работы)"
    folder: "src/content/work" # Убедитесь, что папка именно тут, а не в src/pages/work
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Описание (SEO)", name: "description", widget: "text" }
      - { label: "Обложка (Thumbnail)", name: "thumbnail", widget: "image" }
      - { label: "Текст работы", name: "body", widget: "markdown" }
      - { label: "Шаблон", name: "templateKey", widget: "hidden", default: "work-sub-page" }