backend:
  name: github
  repo: fiodarbardworks/portfolio-site
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"
publish_mode: editorial_workflow
local_backend: true
media_folder: public/img
public_folder: /img

collections:
  - name: "pages"
    label: "Основные страницы"
    delete: false
    files:
      - name: "about"
        label: "Страница About (Bio)"
        file: "src/content/pages/bio.md"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Описание (SEO)", name: "description", widget: "text" }
          - { label: "Текст страницы", name: "body", widget: "markdown" }
          - { label: "Тип страницы", name: "pagetype", widget: "hidden", default: "main" }

      - name: "contact"
        label: "Страница Контакты"
        file: "src/content/pages/contact.md"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Текст страницы", name: "body", widget: "markdown" }
          - { label: "Тип страницы", name: "pagetype", widget: "hidden", default: "main" }

  - name: "works"
    label: "Ваши работы (Works)"
    folder: "src/content/work"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Порядковый номер", name: "number", widget: "number", default: 10 }
      - { label: "Обложка", name: "image", widget: "image" }
      - { label: "Текст работы", name: "body", widget: "markdown" }
      - { label: "Тип страницы", name: "pagetype", widget: "hidden", default: "main" }